inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - "src/**/*"
    - "target/**/*"
    - "tmp/**/*"

Style/GlobalVars:
  Exclude:
    - ext/rubydex/extconf.rb
