name: rubydex
nix: true
up:
  - ruby
  - bundler
  - rust

commands:
  test:
    desc: Run Ruby and Rust test suites via Rake
    run: bundle exec rake test
  lint:
    desc: Run RuboCop and Rust linting
    run: bundle exec rake lint
  format:
    desc: Format Ruby and Rust sources
    run: bundle exec rake format

check:
  all: bundle exec rake check
