# typed: strict
# frozen_string_literal: true

# This file is generated by `generate_ruby_rules.rs`. Do not edit this manually.

module Rubydex
  module Rules
    # Dynamic ancestor references cannot be reasoned about statically because they depend on runtime values. The
    # program may still be valid, but the quality of the analysis degrades. In the case of ancestors, since they
    # influence constant resolution, the degradation may be more impactful than other dynamic references.
    #
    # ```ruby
    # class Foo < var
    #             ^^^ Dynamic ancestor reference. This might be correct, but it cannot be understood by the analysis.
    #   include SomeClass.method_call
    #           ^^^^^^^^^^^^^^^^^^^^^ Dynamic ancestor reference.
    # end
    # ```
    class DynamicAncestor < Rule
      class << self
        # @override
        #: -> singleton(Severity::Base)
        def default_severity
          Severity::Information
        end
      end
    end
  end
end
