# typed: strict
# frozen_string_literal: true

# This file is generated by `generate_ruby_rules.rs`. Do not edit this manually.

module Rubydex
  module Rules
    # Dynamic singleton targets cannot be reasoned about statically because they depend on runtime values. The program
    # may still be valid, but the quality of the analysis degrades.
    #
    # ```ruby
    # class << var
    #          ^^^ Dynamic singleton target. This might be correct, but it cannot be understood by the analysis.
    # end
    #
    # def var.bar
    #     ^^^ Dynamic singleton target.
    # end
    # ```
    class DynamicSingletonDefinition < Rule
      class << self
        # @override
        #: -> singleton(Severity::Base)
        def default_severity
          Severity::Information
        end
      end
    end
  end
end
