# typed: strict
# frozen_string_literal: true

# This file is generated by `generate_ruby_rules.rs`. Do not edit this manually.

module Rubydex
  module Rules
    # A dynamic singleton block target is not necessarily a mistake, but Rubydex cannot reason about it due to its
    # dynamic nature. For example, in `class << var` or `def var.foo`, it's not possible to determine statically what
    # is being defined since `var` is a value that depends on the runtime. Using this type of pattern will degrade the
    # quality of the analysis as Rubydex might be missing some information about how the code truly behaves.
    class DynamicSingletonDefinition < Rule
      class << self
        # @override
        #: -> singleton(Severity::Base)
        def default_severity
          Severity::Information
        end
      end
    end
  end
end
