# typed: strict
# frozen_string_literal: true

# This file is generated by `generate_ruby_rules.rs`. Do not edit this manually.

module Rubydex
  module Rules
    # A dynamic constant reference usage is not necessarily a mistake, but Rubydex cannot reason about it due to its
    # dynamic nature. For example, `var::Foo`. It's not possible to determine what `Foo` is being referred to because
    # `var` is a value that depends on the runtime. Using this type of pattern will degrade the quality of the
    # analysis as Rubydex might be missing some information about how the code truly behaves.
    class DynamicConstantReference < Rule
      class << self
        # @override
        #: -> singleton(Severity::Base)
        def default_severity
          Severity::Information
        end
      end
    end
  end
end
