# typed: strict
# frozen_string_literal: true

# This file is generated by `generate_ruby_rules.rs`. Do not edit this manually.

module Rubydex
  module Rules
    # Reports the usage of a constant visibility operation (`public_constant`, `private_constant`) where either the
    # receiver or the arguments are dynamic and cannot be analyzed statically. For example, in `public_constant(var)`
    # or `var.public_constant(:Foo)`, it's not possible to determine statically what constant is being changed since
    # `var` is a value that depends on the runtime. Using this type of pattern will degrade the quality of the
    # analysis as Rubydex might be missing some information about how the code truly behaves.
    class InvalidConstantVisibility < Rule
      class << self
        # @override
        #: -> singleton(Severity::Base)
        def default_severity
          Severity::Warning
        end
      end
    end
  end
end
