# typed: strict
# frozen_string_literal: true

# This file is generated by `generate_ruby_rules.rs`. Do not edit this manually.

module Rubydex
  module Rules
    # Reports a method visibility call that cannot be applied.
    #
    # `private`, `public`, `protected` and `module_function` need an enclosing namespace and literal arguments.
    # Calling one at the top level or with a computed argument leaves the visibility of the methods unchanged. A
    # wrapped `attr_*` call (`private attr_reader :foo`) is only understood when it is the single argument.
    class InvalidMethodVisibility < Rule
      class << self
        # @override
        #: -> singleton(Severity::Base)
        def default_severity
          Severity::Warning
        end
      end
    end
  end
end
