# typed: strict
# frozen_string_literal: true

# This file is generated by `generate_ruby_rules.rs`. Do not edit this manually.

module Rubydex
  module Rules
    # Method visibility operations that depend on dynamic values cannot be reasoned about statically because they
    # depend on runtime values. The program may still be valid, but the quality of the analysis degrades.
    #
    # ```ruby
    # var.private :foo
    # ^^^ Invalid method visibility. This might be correct, but it cannot be understood by the analysis.
    #
    # private(var)
    #         ^^^ Invalid method visibility.
    # ```
    class InvalidMethodVisibility < Rule
      class << self
        # @override
        #: -> singleton(Severity::Base)
        def default_severity
          Severity::Warning
        end
      end
    end
  end
end
