# typed: strict
# frozen_string_literal: true

# This file is generated by `generate_ruby_rules.rs`. Do not edit this manually.

module Rubydex
  module Rules
    # Parse warnings represent code that has valid syntax, but may not do what the developer expects. For example,
    # local variables that are completely unused or usage in a void context (creating a line of code that does
    # nothing).
    #
    # ```ruby
    # CONST = 1
    # CONST # <<< void context
    # puts CONST + 2
    # ```
    class ParseWarning < Rule
      class << self
        # @override
        #: -> singleton(Severity::Base)
        def default_severity
          Severity::Warning
        end
      end
    end
  end
end
