# typed: strict
# frozen_string_literal: true

# This file is generated by `generate_ruby_rules.rs`. Do not edit this manually.

module Rubydex
  module Rules
    # A parse error represents invalid Ruby syntax and a program that will fail to execute. For example, a missing
    # `end`, an unterminated string, a missing parenthesis.
    class ParseError < Rule
      class << self
        # @override
        #: -> singleton(Severity::Base)
        def default_severity
          Severity::Error
        end
      end
    end
  end
end
