# typed: strict
# frozen_string_literal: true

# This file is generated by `generate_ruby_rules.rs`. Do not edit this manually.

module Rubydex
  module Rules
    # The top level of a Ruby program is the special <main> object. It is not possible to use `include self` or
    # `extend self` on that object.
    class TopLevelMixinSelf < Rule
      class << self
        # @override
        #: -> singleton(Severity::Base)
        def default_severity
          Severity::Information
        end
      end
    end
  end
end
