# typed: strict
# frozen_string_literal: true

# This file is generated by `generate_ruby_rules.rs`. Do not edit this manually.

module Rubydex
  module Rules
    # Undefined constant visibility target means the analysis couldn't find the definition for the constant the code is
    # attempting to change visibility of. It could be defined through meta-programming or it indeed does not exist.
    #
    # ```ruby
    # class Foo
    #   private_constant :Bar
    #                    ^^^ Undefined constant visibility target. The constant `Bar` is not defined.
    # end
    # ```
    class UndefinedConstantVisibilityTarget < Rule
      class << self
        # @override
        #: -> singleton(Severity::Base)
        def default_severity
          Severity::Warning
        end
      end
    end
  end
end
