# typed: strict
# frozen_string_literal: true

# This file is generated by `generate_ruby_rules.rs`. Do not edit this manually.

module Rubydex
  module Rules
    # Reports a constant visibility change naming a constant the namespace does not have.
    #
    # The call itself was understood and its target namespace resolved, but no constant by that name was ever defined
    # there, so there is nothing to change. This is usually a typo or a leftover from a constant that was removed.
    class UndefinedConstantVisibilityTarget < Rule
      class << self
        # @override
        #: -> singleton(Severity::Base)
        def default_severity
          Severity::Warning
        end
      end
    end
  end
end
