# typed: strict
# frozen_string_literal: true

# This file is generated by `generate_ruby_rules.rs`. Do not edit this manually.

module Rubydex
  module Rules
    # Reports a method visibility operation naming a method that doesn't exist in the namespace. For example, `private
    # :foo`, where `foo` is not defined anywhere in the ancestor chain of the owner.
    class UndefinedMethodVisibilityTarget < Rule
      class << self
        # @override
        #: -> singleton(Severity::Base)
        def default_severity
          Severity::Warning
        end
      end
    end
  end
end
