#ifndef RUSTBINDINGS_H
#define RUSTBINDINGS_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef void CRepository;

typedef struct CEntry {
    char *name;
    char *value;
} CEntry;

CRepository *get_repository(void);

struct CEntry *repository_get_entry(const CRepository *repository, const char *name);

void repository_add_entry(CRepository *repository, const char *name, const char *value);

void dealloc_entry(struct CEntry *entry);

void dealloc_repository(CRepository *repository);

#endif /* RUSTBINDINGS_H */
