#ifndef RUSTBINDINGS_H
#define RUSTBINDINGS_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

void index_all_c(char **file_paths, size_t count);

#endif /* RUSTBINDINGS_H */
