#ifndef RUSTBINDINGS_H
#define RUSTBINDINGS_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef void CRepository;

typedef void CEntry;

CRepository *get_repository(void);

CEntry *repository_get_entry(const CRepository *repository, const char *name);

void repository_add_entry(CRepository *repository, const char *name, const char *value);

const char *entry_get_name(const CEntry *entry);

const char *entry_get_value(const CEntry *entry);

void delloc_entry(CEntry *entry);

void dealloc_repository(CRepository *repository);

#endif /* RUSTBINDINGS_H */
